base_model: /home/ubuntu/llm_models/vicuna-7b-v1.5
base_model_config: /home/ubuntu/llm_models/vicuna-7b-v1.5
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: /home/ubuntu/proj/graphbert/data/pubmed/train.jsonl
    has_soft: true
    pos_path: /home/ubuntu/proj/graphbert/data/pubmed/train.pt
    type: alpaca
dataset_prepared_path:
val_set_size: 0.05
output_dir: ./pubmed/qlora-out-vicuna-7b-v1.5

adapter: softprompt
adapter_model_dir:

sequence_len: 256
sample_packing: false
pad_to_sequence_len: true

softprompt_input_embedding_dim: 768
softprompt_num_pos_tokens: 1
softprompt_num_virtual_tokens: 4
softprompt_encoder_hidden_size: 1024

wandb_project:
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 8
num_epochs: 5
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 0.05
eval_table_size:
save_steps: 2000
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
